### ISSUE TITLE
Calibration Grid

### ISSUE THREAD

**Issue by jominga** [mkalten/reacTIVision#14]
Hello,

I used the grid calibration option of Reactivision because I'm using a Fisheye camera and I also want to ignore some parts of the picture captured by it. However the positions of the blobs I receive in my client are the same before and after the calibration.

Am I missing an intermediate step?
Thanks in advance!

<img width="1025" alt="captura de pantalla 2016-04-18 a las 11 02 04" src="https://cloud.githubusercontent.com/assets/7756809/14599132/e9353384-0555-11e6-857f-63879e5702e5.png">

**Comment by mkalten** [comment]
Hi, the current development branch still doesn't correct the distortion for finger and blobs. Since this is quite trivial to add, I implement the according updates as soon as possible ...

**Comment by mkalten** [comment]
I just pushed a quick update including the according min_size configuration option for the blobs,
let me know if this works for you ... I didn't have time to test it much yet

**Comment by jominga** [comment]
It works! Thank you very much!

**Comment by mkalten** [comment]
@jominga ... finally I managed to commit the proper blob/finger calibration update as well.
let me know if everything works as expected, so we can close this issue

**Comment by jominga** [comment]
It works like charm. Thank you very much! 

And I will move the camera closer, thanks for the advice!
