### ISSUE TITLE
Grid result deforming

### ISSUE THREAD

**Issue by PabloArty** [mkalten/reacTIVision#15]
Hello MK! I have to tell you that i'm using reactivision since 2012 and i love it! Now, my problem is when I try to adjust the wide 16:9 grid the result is all deformed and it looks like a mess.

This is the grid adjusted:
![20160419_125658](https://cloud.githubusercontent.com/assets/6517199/14649894/bd0bb02e-062e-11e6-8940-872ebbdb77b4.jpg).

And this is the result:
![20160419_125705](https://cloud.githubusercontent.com/assets/6517199/14649913/cf86d8d2-062e-11e6-8baf-1a7984055e13.jpg)

Thanks for all bro! Have a nice week!

**Comment by mkalten** [comment]
This is a know issue, which is already fixed. There will be a 1.5.1 maintenance release soon, and you can already download a test build for mac and windows from here: 

https://github.com/mkalten/reacTIVision/releases/tag/1.5

Please let me know if this works for you, so I can push out the formal release soon.

**Comment by PabloArty** [comment]
That's a detail here, I just download the 1.5 master folder and replaced all the files for windows, and it's not working, BUT i don't know if i need to compile the visual studio project to see the updates working.

**Comment by mkalten** [comment]
No need to compile, as I said there is also a test build for windows here:
https://github.com/mkalten/reacTIVision/releases/download/1.5/reacTIVision-1.5.1-win32.zip

**Comment by PabloArty** [comment]
Well I tested the windows compiled version and all is good now. If I found more bugs I tell you. Thank's bro!
