### ISSUE TITLE
Visual Studio not compiling

### ISSUE THREAD

**Issue by jominga** [mkalten/reacTIVision#16]
Hello,

I need to run the reacTIVision server on windows, but Visual Studio gives me the following compile error:

> Error C2371: 'int32_t': redefinition; different basic types

The error comes up in TcpSender.cpp in the first code lines:

```
#ifdef  WIN32
#ifndef int32_t
typedef DWORD int32_t;
#endif
#endif
```

Any help?

**Comment by mkalten** [comment]
you are brave, I just rewrote the whole windows camera driver implementation.
I also removed this apparently obsolete definition, so everything should work fine now.

BTW, please try the new interactive camera setup feature, by pressing 'K'

**Comment by jominga** [comment]
It compiles now, thank you very much!
