### ISSUE TITLE
wrong dimensions from camera

### ISSUE THREAD

**Issue by nylki** [mkalten/reacTIVision#24]
continuing the other issue: 
`sudo modprobe bcm2835-v4l2` on raspberry pi 3 with latest rasbian and picam2 worked. Tested it with the `motion` tool to capture frames via v4l2.

However when starting reactivision 1.5.1 I get a wrong camera resolution (848x32 with a framerate of 30FPS). Setting any manual width/height in the `camera.xml` results in this dimension. When doing `capture width="max" height="max"` it actually works sometimes, sometimes it crashes. It reports 3280x2462.
 The maximum width/height might be much for the raspberrypi to handle.

I also tried reducing the framerate to 15fps but the option seems to be ignored and is set back to 90fps.

Is there something I might be missing?

**Comment by mkalten** [comment]
you can list all available formats with reacTIVision -l
it's a long list since the raspicam driver only provides stepwise image formats, no standard resolutions ... you should be able to choose any of those combinations shown

**Comment by nylki** [comment]
thank you, choosing a resolution form the list and entering the values into the XML worked just fine!
