### ISSUE TITLE
Low fps on Raspberry Pi

### ISSUE THREAD

**Issue by pi-bansal** [mkalten/reacTIVision#31]
Reactivision 1.5 armhf when installed on Raspberry Pi is giving 2 to 3 fps.
Reactivision 1.4 when compiled from source gives 30 fps which is good but gets crashed.

**Comment by mkalten** [comment]
this depends on the graphic acceleration, which is apparently not working on your raspi distro.
if you turn off the display (pressing N) you can see the full frame rate ...
alternatively you can recompile the SDL library to enable hardware acceleration for the display.

**Comment by pi-bansal** [comment]
Ok, I will check the graphic acceleration and see how to recompile SDL library
