### ISSUE TITLE
No object in Pure Data    No connect no data

### ISSUE THREAD

**Issue by arpeggio1234** [mkalten/reacTIVision#32]
hello, i am on Linux, Manjaro, and use ReacTIVision (this works good).
And then i start Pd (Pd-L2ork)and when i load a sketch it says: couldn't create,
so Pd can not create the tuioclient object, 
i used the 1.1.5 zip and the later 1.3 zip and still no succes.
I just load the things from the unpacked zip folder. 
Can someone help me out here please, i searched a lot but still the same.
the tuioclient object will not create.
Do i miss something; a library or is it just a Pd thing, where do i have to put the files.
Many thanks, Dian

**Comment by mkalten** [comment]
which platform are you using? maybe you just need to recompile the pd external
1.1.5 is the latest version ...

**Comment by arpeggio1234** [comment]
I got it working. Had to make the tuioclient.pd_linux file 
And then pd could create the tuioclient object.
Great. Thanks for your support.
Dian
----- Oorspronkelijk bericht -----
Van: Martin Kaltenbrunner <notifications@github.com>
Aan: mkalten/reacTIVision <reacTIVision@noreply.github.com>
Cc: arpeggio1234 <dianderocker@online.nl>, Author <author@noreply.github.com>
Verzonden: Tue, 08 May 2018 10:48:20 +0200 (CEST)
Onderwerp: Re: [mkalten/reacTIVision] No object in Pure Data No connect no data (#32)

which platform are you using? maybe you just need to recompile the pd external
1.1.5 is the latest version ...
