### ISSUE TITLE
reactivision+Tuio with Processing.org

### ISSUE THREAD

**Issue by Judithricketts** [mkalten/reacTIVision#33]
Hello, my first question here! I am a Student, new to programming I would like to use reactivision+ Tuio with Processing.org.  I understand I need to use Processing 2.0 (is is correct?)  but cannot get Processing to recognise the presence of the reactivision library. Would you please firstly walk me through the install process then the set up process, laypersons language please....appriciated

**Comment by mkalten** [comment]
Hello Judith, you can use the TUIO client for Processing with version 2 and 3.
Just install the necessary library from here: https://github.com/mkalten/TUIO11_Processing
