### ISSUE TITLE
Visual Studio 2017 support

### ISSUE THREAD

**Issue by toshinoritakata** [mkalten/reacTIVision#38]
Hi everyone.

How about changing VisualStudo2017 to be the official compiler used to build the Windows version?
VisualStudio 2012 is old and there is no community version, which limits the number of people who can build it.

When compiling the master branch with VS2017, the following error occurs, but I was able to solve the error by rebuilding libusb with VS2017.

``''
Error LNK2001 unresolved external symbol ___iob_func reacTIVision reacTIVision\cTIVisionwindowslibusb-1.0.lib(core.obj) 1	
Error LNK2001 unresolved external symbol _sscanf reacTIVision reacTIVision	
Error LNK1120 2 unresolved externals reacTIVision reacTIVision reacTIVision reacTIVision Windows\blur32DebugreacTIVision.exe 1.	
````

**Comment by mkalten** [comment]
the VS solution/project, and the SDL and USB libraries are now updated for VS2017
