### ISSUE TITLE
Crash on OSX 10.10

### ISSUE THREAD

**Issue by jceipek** [mkalten/reacTIVision#4]
reacTIVision 1.5 (Nov  6 2014)

no DC1394 cameras found
1 AVFoundation camera found
2015-04-02 22:53:10.846 reacTIVision[2775:42460] CameraControl Error: IOCreatePlugInInterfaceForService returned 0xe00002be.
fish: Job 1, './reacTIVision' terminated by signal SIGSEGV (Address boundary error)

I tried building the application myself and this seems to be happening on line 468 of `VVUVCController.m` - `EXC_BAD_ACCESS`. I assume that the problem lies with https://github.com/mrRay/VVUVCKit? By the way, could you please add that dependency to the readme?

**Comment by mkalten** [comment]
hello, I just updated the VVUVCKit framework and added a comment to the README as you suggested.
let me know if that problem persists ...
