### ISSUE TITLE
ReacTIvision not working because of Tangible Interaction Framework

### ISSUE THREAD

**Issue by G0NI25** [mkalten/reacTIVision#42]
For some weird reason, the program crashes because the Tangible Interaction Framework stops working, I geniunely have no clue what that even is, is it something related to the NET framework?

Also, I wanna point out that I am using Windows 7.

Would gladly appreciate help :)

![20220612_204023](https://user-images.githubusercontent.com/107368449/173250416-51104b0e-4043-403c-950b-6e0ca7b716ed.jpg)

**Comment by seeacloud** [comment]
您好，您的邮件我已经收到，我会尽快回复您。谢谢！

**Comment by floe** [comment]
@seeacloud would you mind turning off your email autoresponder?

**Comment by floe** [comment]
@G0NI25 "Tangible Interaction Framework" is just the long name for the reacTIVision executable. We'd need a bit more information about the crash, but I wouldn't know how to find that on Windows 7 - have you tried starting from the console?
