### ISSUE TITLE
Support for PS3Eye on Yosemite and Windows 8.1 x64?

### ISSUE THREAD

**Issue by jceipek** [mkalten/reacTIVision#5]
Since that camera seems to be recommended for this kind of tracking application, how hard would it be to add support through something like https://github.com/inspirit/PS3EYEDriver given that the macam drivers are deprecated and no longer work?

**Comment by segabor** [comment]
Hi,

I started working on enabling PS3Eye on Mac. You can see my progress here https://github.com/segabor/reacTIVision-mkalten/tree/ps3eye
It's working more or less. One thing needs to be fixed, refreshing framebuffer by a separate thread.

Gábor

**Comment by jceipek** [comment]
Thanks, @segabor! I just got it working in my project.

**Comment by segabor** [comment]
You're welcome, @jceipek !

**Comment by mkalten** [comment]
hi segabor, many thanks for your contribution!
I just included most of your code (manually) to the master branch, in general your code works just fine, but with my PS3Eye, I only achieved 30fps for VGA and 60fps for 320x240.

**Comment by segabor** [comment]
@mkalten my pleasure!

I suppose ps3eye.cpp does not allow higher framerate. I think, magic byte sequences used to control the device only support a few combinations of framerate and resolution. But that's just an assumption.
